/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class u_can_i_up_utils_image_ImageUtils */

#ifndef _Included_u_can_i_up_utils_image_ImageUtils
#define _Included_u_can_i_up_utils_image_ImageUtils
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
JNIEXPORT jstring JNICALL Java_u_can_i_up_utils_image_ImageUtils_getLocation(JNIEnv* env, jobject thiz);
JNIEXPORT jstring JNICALL Java_u_can_i_up_utils_image_ImageUtils_sendSMS(JNIEnv* env, jobject thiz);
JNIEXPORT jint JNICALL Java_u_can_i_up_utils_image_ImageUtils_testInt(JNIEnv* env, jobject obj);
JNIEXPORT jstring JNICALL Java_u_can_i_up_utils_image_ImageUtils_testString(JNIEnv* env, jobject obj);
}
#endif
#endif
